# conda environment setup YAML
name: paper-helper-salado-2021
channels:
  - bioconda
  - conda-forge
dependencies:
  # For their scripts
  - biopython>=1.79,<2
  - r
  - r-ggplot2
  - r-arsenal
  # For MEGASAT
  - perl
  - perl-parallel-forkmanager
  # For CHIIMP
  - pandoc
  # For my own code here
  - sra-tools>=2.11,<3
  - snakemake
