# conda environment setup YAML
name: paper-helper-salado-2021
channels:
  - bioconda
  - conda-forge
dependencies:
  # For their scripts
  - biopython>=1.79,<2
  - r
  - r-ggplot2
  - r-arsenal
  # For MEGASAT
  - perl
  - perl-parallel-forkmanager
  # For CHIIMP
  - cutadapt>=4.0,<5
  - pandoc
  - r-argparser
  - r-devtools
  - r-kableextra
  - r-knitr
  - r-pheatmap
  - r-viridis
  - r-yaml
  # For my own code here
  - sra-tools>=2.11,<3
  - snakemake>=7.6,<8
  # Just for convenience
  - seqmagick
